// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Bookmark struct {
	TweetID  int64
	Username string
}

type Like struct {
	TweetID  int64
	Username string
}

type Tweet struct {
	TweetID       int64
	Author        string
	Content       string
	Created       sql.NullTime
	LikeCount     int64
	ParentTweetID sql.NullInt64
}
